version: '3.9'

services:
  mysqldb:
    container_name: mysqldb
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldb:/docker-entrypoint-initdb.d/:ro

  shortener_app:
    container_name: app
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_URL: "mysql+asyncmy://root:root@mysqldb:3306/shortener_url"
    volumes:
      - ./backend/:/backend/
    ports:
      - 5000:5000
    depends_on:
      - mysqldb
    command: sh -c "sleep 20s; uvicorn shortener_app.main:app --proxy-headers --host 0.0.0.0 --port 5000"

