version: '3.9'
services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/backend/
    command: uvicorn shortener_app.main:app --workers 4 --proxy-headers --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
  db:
    image: mysql
    ports:
      - "3307:3307"
    env_file:
      - ./backend/.env