version: '3'

services:
  db:
    container_name: db
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shortener_url
    ports:
      - '5433:5433'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/postgres_db/init.sql

  shortener_app:
    container_name: app
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_URL: "postgresql+asyncpg://username:password@db:5432/shortener_url"
    volumes:
      - ./backend/:/backend/
    ports:
      - 5000:5000
    depends_on:
      - db
    command: sh -c "sleep 20s; uvicorn shortener_app.main:app --proxy-headers --host 0.0.0.0 --port 5000"
